default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres_user
  password: postgres_pass

development:
  <<: *default
  database: ba_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: ba_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: ba_production
  username: <%= ENV['BA_DATABASE_USERNAME'] %>
  password: <%= ENV['BA_DATABASE_PASSWORD'] %>