require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/NestedGroups:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
  Exclude: 
    - 'db/seeds.rb'
